// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJIau_edXIl9HbGBglcTcFbg6C97_yDuo',
    appId: '1:1073912278037:web:37eaeebada8f3f2f81f21c',
    messagingSenderId: '1073912278037',
    projectId: 'kuk-book',
    authDomain: 'kuk-book.firebaseapp.com',
    storageBucket: 'kuk-book.firebasestorage.app',
    measurementId: 'G-TQB7XLP7EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6OygKdsM75D_4TrqQ5sZKocXzsdNtw64',
    appId: '1:1087665065290:android:5adff733a9752f1fad45b3',
    messagingSenderId: '1087665065290',
    projectId: 'food-ninja-84da7',
    storageBucket: 'food-ninja-84da7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaPYv4e1Bn81CKdGJ0c_TsnCvpxRO2b6A',
    appId: '1:1073912278037:ios:0b94440f1f8fe3c281f21c',
    messagingSenderId: '1073912278037',
    projectId: 'kuk-book',
    storageBucket: 'kuk-book.firebasestorage.app',
    iosBundleId: 'com.example.kukbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaPYv4e1Bn81CKdGJ0c_TsnCvpxRO2b6A',
    appId: '1:1073912278037:ios:0b94440f1f8fe3c281f21c',
    messagingSenderId: '1073912278037',
    projectId: 'kuk-book',
    storageBucket: 'kuk-book.firebasestorage.app',
    iosBundleId: 'com.example.kukbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJIau_edXIl9HbGBglcTcFbg6C97_yDuo',
    appId: '1:1073912278037:web:e81e2ae8a24f370281f21c',
    messagingSenderId: '1073912278037',
    projectId: 'kuk-book',
    authDomain: 'kuk-book.firebaseapp.com',
    storageBucket: 'kuk-book.firebasestorage.app',
    measurementId: 'G-8WTK47MC83',
  );
}